#!/usr/bin/env bash
# =============================================================================
# init.sh — Initialize CADRE in a project
#
# Usage:
#   bash scripts/init/init.sh
#
# Creates:
#   - cadre-config.yml (agent limits)
#   - .git/hooks/ (CADRE hooks)
#   - tasks/ directory structure
#   - specs/ directory structure
# =============================================================================

set -euo pipefail

ORIG_CWD="$(pwd)"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CADRE_ROOT="$(dirname "$(dirname "$SCRIPT_DIR")")"

PROJECT_DIR="${1:-$ORIG_CWD}"

echo "=== CADRE Init ==="
echo "Project: $PROJECT_DIR"
echo ""

cd "$PROJECT_DIR" || exit 1

# Check git
if [[ ! -d .git ]]; then
    echo "Error: Not a git repository. Run git init first." >&2
    exit 1
fi

# -----------------------------------
# 1. Create cadre-config.yml
# -----------------------------------
if [[ -f cadre-config.yml ]]; then
    echo "⚠️  cadre-config.yml already exists. Skipping."
else
    echo "Creating cadre-config.yml..."
    cat > cadre-config.yml <<'EOF'
# CADRE Configuration
# Generated by CADRE init

agents:
  # Maximum total agents running in parallel
  max_total: 5
  
  # Maximum agents per type (module agents are dynamic per project)
  max_per_type: 3

sprint:
  # Branch naming
  branch_prefix: sprint
  
  # PR target
  target_branch: main

hooks:
  # Enable CADRE hooks
  enabled: true
  
  # Pre-push checks
  run_tests: true
  run_lint: true
  
  # Auto-create PR for microbranches
  auto_pr: false

tasks:
  # Task file location
  directory: tasks
  
  # Microbranch prefix
  micro_prefix: micro

EOF
    echo "  → cadre-config.yml created"
fi

# -----------------------------------
# 2. Setup Git Hooks
# -----------------------------------
if [[ -f "$SCRIPT_DIR/setup-hooks.sh" ]]; then
    echo "Installing CADRE hooks..."
    bash "$SCRIPT_DIR/setup-hooks.sh"
    echo "  → hooks installed"
else
    echo "⚠️  setup-hooks.sh not found. Skipping hooks."
fi

# -----------------------------------
# 3. Create directory structure
# -----------------------------------

# Agents directory (project-specific agents)
if [[ ! -d agents ]]; then
    mkdir -p agents
    cat > agents/README.md <<'EOF'
# Agents Directory

## Project-Specific Agents

Each agent is defined in its own subdirectory:
\`\`\`
agents/
├── api-dev/         # API developer agent
│   ├── context.md  # Agent context and skills
│   └── ...         # Other agent-specific files
├── frontend-dev/   # Frontend developer agent
├── infra-dev/      # Infrastructure agent
└── ...
\`\`\`

## Agent Naming

Agent names are taken from:
1. Task's `module:` field
2. Directory names in agents/

## Usage

When spawning agents, CADRE looks in agents/ for:
- Agent context (context.md)
- Agent-specific configurations
- Skills and competencies
EOF
    echo "  → agents/ created"
else
    echo "⚠️  agents/ already exists. Skipping."
fi

# Tasks directory
if [[ ! -d tasks ]]; then
    mkdir -p tasks
    cat > tasks/README.md <<'EOF'
# Tasks Directory

## Task File Format

\`\`\`markdown
---
title: "[T001] Task title"
status: TODO
priority: P1
module: api-dev
created-by: puma
---

## Description
What needs to be done.

## Files
- \`api/...\`

## Dependencies
- T000

## Verification
How to verify done.
\`\`\`

## Status Flow
TODO → IN_PROGRESS → READY_FOR_REVIEW → DONE
EOF
    echo "  → tasks/ created"
else
    echo "⚠️  tasks/ already exists. Skipping."
fi

# Specs directory
if [[ ! -d specs ]]; then
    mkdir -p specs
    cat > specs/README.md <<'EOF'
# Specs Directory

## Epic Structure
Each epic has its own folder:
\`\`\`
specs/
├── S1-epic-name/
│   ├── spec.md
│   ├── plan.md
│   ├── tasks/
│   ├── contracts/
│   └── assessment-report.md
\`\`\`
EOF
    echo "  → specs/ created"
else
    echo "⚠️  specs/ already exists. Skipping."
fi

# -----------------------------------
# CADRE Structure Summary
# -----------------------------------
echo ""
echo "=== CADRE Structure ==="
echo ""
echo "Your project now has:"
echo "  agents/      - Project-specific agents (api-dev, frontend-dev, etc)"
echo "  tasks/       - Task files (T001.md, T002.md, ...)"
echo "  specs/       - Epic specs and plans"
echo "  cadre-config.yml - CADRE configuration"
echo ""
echo "Agent names come from:"
echo "  1. Task's module: field (e.g., module: api-dev)"
echo "  2. Directory names in agents/"
echo ""
echo "Next:"
echo "  1. Define your agents in agents/"
echo "  2. Run sprint-plan.sh to create epic"
echo "  3. Run implement.sh to spawn agents"

# -----------------------------------
# 4. Create .gitignore entries
# -----------------------------------
echo ""
echo "=== Adding to .gitignore ==="

GITIGNORE=".gitignore"
CADRE_IGNORE='
# CADRE
cadre-config.yml
tasks/*.md
!tasks/README.md
specs/
*.cadre.bak
'

if [[ -f "$GITIGNORE" ]]; then
    if ! grep -q "CADRE" "$GITIGNORE"; then
        echo "$CADRE_IGNORE" >> "$GITIGNORE"
        echo "  → Added CADRE entries to .gitignore"
    else
        echo "⚠️  CADRE already in .gitignore"
    fi
else
    echo "$CADRE_IGNORE" > "$GITIGNORE"
    echo "  → Created .gitignore with CADRE entries"
fi

# -----------------------------------
# Summary
# -----------------------------------
echo ""
echo "✅ CADRE Init Complete!"
echo ""
echo "Created:"
echo "  - cadre-config.yml"
echo "  - .git/hooks/ (CADRE hooks)"
echo "  - tasks/"
echo "  - specs/"
echo ""
echo "Next:"
echo "  1. Edit cadre-config.yml if needed"
echo "  2. Run: bash sprint-plan.sh <epic>"
