#!/usr/bin/env bash
# =============================================================================
# puma-init.sh — Initialize Puma context for a project
#
# Usage: bash scripts/bash/puma-init.sh <project-path>
#
# Example: bash scripts/bash/puma-init.sh /workspace/projects/specforge
#
# Creates puma-context.md with project context from spec.md
# =============================================================================

set -euo pipefail

PROJECT_PATH="${1:-}"

if [[ -z "$PROJECT_PATH" ]]; then
  echo "Usage: puma-init.sh <project-path>" >&2
  exit 1
fi

if [[ ! -d "$PROJECT_PATH" ]]; then
  echo "Project not found: $PROJECT_PATH" >&2
  exit 1
fi

# Check for PROJECT-SPEC.md or specs/*/spec.md
if [[ -f "$PROJECT_PATH/PROJECT-SPEC.md" ]]; then
  SPEC_FILE="$PROJECT_PATH/PROJECT-SPEC.md"
elif [[ -f "$PROJECT_PATH/specs/"*/spec.md ]]; then
  SPEC_FILE="$PROJECT_PATH/specs/"*/spec.md
else
  echo "No spec file found (PROJECT-SPEC.md or specs/*/spec.md)" >&2
  exit 1
fi

echo "=== Puma Init ==="
echo "Project: $PROJECT_PATH"
echo "Reading: $SPEC_FILE"

# Extract relevant info from spec.md
PROJECT_NAME=$(grep -m1 "^# " "$SPEC_FILE" | sed 's/^# //' || echo "Unknown Project")
DOMAIN=$(grep -m1 "^## " "$SPEC_FILE" | sed 's/^## //' || echo "Unknown Domain")
GOAL=$(grep -A5 "^## Goal" "$SPEC_FILE" | head -6 | tail -5 | sed 's/^#*//' || echo "See spec.md")
STACK=$(grep -A10 "^## Stack" "$SPEC_FILE" | head -10 | tail -8 | sed 's/^#*//' || echo "See spec.md")

# Create puma-context.md
OUTPUT_FILE="$PROJECT_PATH/puma-context.md"

cat > "$OUTPUT_FILE" <<EOF
# Puma Context — $PROJECT_NAME

**Initialized**: $(date '+%Y-%m-%d')
**Source**: $SPEC_FILE

---

## Project Overview

**Name**: $PROJECT_NAME
**Domain**: $DOMAIN

## Goal

$GOAL

## Stack

$STACK

## Non-Technical Notes

[TODO: Add product-specific notes, user personas, constraints]

## Task Creation Guidelines

[TODO: Add project-specific task creation patterns]

---

_Puma Context — Generated by puma-init.sh_
EOF

echo "Created: $OUTPUT_FILE"
echo ""
echo "=== Init Complete ==="
echo "Review and update: $OUTPUT_FILE"
